version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:xxxxxxxxxxxxxxxxxxxxxxxxxx
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: invoicedb
      DB_USERNAME: root
      DB_PASSWORD: ee5f161511d513648dbef9f50f3f9a98

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: invoicedb
      MYSQL_USER: root
      MYSQL_PASSWORD: ee5f161511d513648dbef9f50f3f9a98
